#server:
#  port: 8002
#
#spring:
#  application:
#    name: service-order
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.242.131:3306/seata_order?serverTimezone=UTC
#    username: root
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#    alibaba:
#      seata:
#        # 自定义事务组名称需要与 seata-server 中的对应
#        tx-service-group: fsp_tx_group
#  # 日志时间：格林威治时间 + 8小时
#  jackson:
#    time-zone: GMT+8
#
#logging:
#  level:
#    io:
#      seata: info
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#
##设置feign客户端超时时间(OpenFeign默认支持ribbon)
#ribbon:
#  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
#  ReadTimeout: 5000
#  #指的是建立连接后从服务器读取到可用资源所用的时间
#  ConnectTimeout: 5000
#
#mybatis-plus:
#  type-aliases-package: com.nlx.mall.domain
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl